// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for FeatureFlagFunction
 */
export interface FeatureFlagFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/feature-flag.
 */
export class FeatureFlagFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: FeatureFlagFunctionProps) {
    super(scope, id, {
      description: 'src/feature-flag.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs14.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../assets/feature-flag.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}